name = "dare"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieAutoReload = "c6228e60-a24f-11e9-1776-c313472ebacc"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StipplePlotly = "ec984513-233d-481d-95b0-a3b58b97af2b"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
